import React, { useState, useEffect } from 'react';
import { Radar, Activity, Download, Shield, AlertOctagon, Languages } from 'lucide-react';
import { AnalysisData, LoadingState } from './types';
import { generateAnalysis } from './services/geminiService';
import Timeline from './components/Timeline';
import AnalysisSection from './components/AnalysisSection';

// Updated Prompt to reflect new depth requirements
const INITIAL_PROMPT = "总结过去7天内，中日之间围绕日本首相“台湾问题”的敏感发言后的重要动作节点。扩大搜索范围至中、日、美三方官方网站（外交部/国防部）及全球主流媒体（含YouTube深度分析）。分析：1）日本首相个人冲动发言的可能性概率和原因分析 2）分析结论确认：给定这次是有计划的行动，目标是“日本正式进入军事化时代，突破二战后的秩序限制，为此需要一次决战式的冲突”。3）预测接下来的中日对抗的进展 4）深度军事分析：参考二战作战模式及美日现代军事理论，分析日本偷袭中国军事目标的可能性、具体模式及潜在目标。";

const TRANSLATIONS = {
  en: {
    title: "Sino-Japanese Strategic Crisis Analysis",
    subtitle: "Advanced intelligence synthesis: Official Gov Sources (CN/JP/US), Multi-Language Media Analysis, and Military Doctrine Simulation.",
    initiate: "INITIATE DEEP SCAN",
    scanning: "SCANNING OFFICIAL CHANNELS (MOFA/MOD/WHITEHOUSE)...",
    timelineTitle: "Operational Timeline (T-7 Days)",
    reportTitle: "Strategic Assessment Report",
    disclaimer: "CONFIDENTIALITY NOTICE: This report is generated by an AI system based on specific hypothetical parameters provided by the user (\"The Takaichi Hypothesis\"). Predictions and feasibility assessments are simulated exercises and do not reflect confirmed government intelligence or absolute certainty.",
    errorTitle: "System Failure",
    retry: "Retry Operation",
    export: "EXPORT VISUAL",
    access: "RESTRICTED ACCESS // EYES ONLY"
  },
  zh: {
    title: "中日战略危机深度分析",
    subtitle: "高级情报综合：官方政府来源（中/日/美）、多语言媒体分析及军事理论推演。",
    initiate: "启动深度扫描",
    scanning: "正在扫描官方渠道 (外交部/防卫省/白宫)...",
    timelineTitle: "行动时间轴 (过去7天)",
    reportTitle: "战略评估报告",
    disclaimer: "保密声明：本报告由AI系统基于用户提供的特定假设参数（“高市早苗假设”）生成。预测和可行性评估均为模拟演练，不反映经确认的政府情报或绝对确定性。",
    errorTitle: "系统故障",
    retry: "重试操作",
    export: "导出视图",
    access: "绝密访问 // 仅限阅览"
  }
};

const App: React.FC = () => {
  const [loadingState, setLoadingState] = useState<LoadingState>({ status: 'idle' });
  const [data, setData] = useState<AnalysisData | null>(null);
  const [lang, setLang] = useState<'zh' | 'en'>('zh');

  const t = TRANSLATIONS[lang];

  const handleGenerate = async () => {
    setLoadingState({ status: 'loading' });
    try {
      const result = await generateAnalysis(INITIAL_PROMPT, lang);
      setData(result);
      setLoadingState({ status: 'success' });
    } catch (error) {
      setLoadingState({ 
        status: 'error', 
        message: error instanceof Error ? error.message : "An unknown error occurred" 
      });
    }
  };

  const toggleLanguage = () => {
    setLang(prev => prev === 'zh' ? 'en' : 'zh');
  };

  useEffect(() => {
     // handleGenerate(); 
     // Auto-load disabled to allow user to initiate.
  }, []);

  return (
    <div className="min-h-screen bg-slate-900 text-slate-200 font-sans selection:bg-red-900 selection:text-white">
      
      {/* Header / Nav */}
      <nav className="sticky top-0 z-50 bg-slate-900/90 backdrop-blur border-b border-slate-800">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex items-center justify-between h-16">
            <div className="flex items-center gap-2">
              <Radar className="h-8 w-8 text-red-500" />
              <span className="text-xl font-bold tracking-tight text-white">
                INTEL<span className="text-red-500">OPS</span> DASHBOARD
              </span>
            </div>
            <div className="flex items-center gap-4">
               <span className="hidden md:block text-xs font-mono text-slate-500">{t.access}</span>
               <button 
                 onClick={toggleLanguage}
                 className="p-2 text-slate-400 hover:text-white transition-colors flex items-center gap-2 border border-slate-700 rounded-md bg-slate-800 hover:bg-slate-700"
               >
                 <Languages className="w-4 h-4" />
                 <span className="text-xs font-bold">{lang.toUpperCase()}</span>
               </button>
            </div>
          </div>
        </div>
      </nav>

      <main className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        
        {/* Hero / Control Section */}
        <div className="mb-12 text-center">
          <h1 className="text-3xl md:text-4xl font-serif font-bold text-white mb-4">
            {t.title}
          </h1>
          <p className="max-w-2xl mx-auto text-slate-400 mb-8 text-sm leading-relaxed">
            {t.subtitle}
          </p>
          
          {loadingState.status === 'idle' && (
            <button 
              onClick={handleGenerate}
              className="group relative inline-flex items-center justify-center px-8 py-3 text-base font-medium text-white bg-red-900 border border-transparent rounded-md hover:bg-red-800 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500 focus:ring-offset-slate-900 transition-all shadow-lg shadow-red-900/30"
            >
              <Shield className="w-5 h-5 mr-2 -ml-1 animate-pulse" />
              {t.initiate}
            </button>
          )}

          {loadingState.status === 'loading' && (
             <div className="flex flex-col items-center justify-center space-y-4">
                <div className="w-12 h-12 border-4 border-red-900 border-t-red-500 rounded-full animate-spin"></div>
                <span className="text-xs font-mono text-red-400 animate-pulse">
                    {t.scanning}
                </span>
             </div>
          )}

          {loadingState.status === 'error' && (
            <div className="bg-red-900/20 border border-red-800 text-red-200 px-6 py-4 rounded-md max-w-lg mx-auto flex items-start gap-3">
              <AlertOctagon className="w-6 h-6 flex-shrink-0" />
              <div className="text-left">
                <h3 className="font-bold text-sm uppercase tracking-wide mb-1">{t.errorTitle}</h3>
                <p className="text-sm">{loadingState.message}</p>
                <button onClick={handleGenerate} className="mt-3 text-xs underline hover:text-white">{t.retry}</button>
              </div>
            </div>
          )}
        </div>

        {/* Main Content */}
        {data && (
          <div className="space-y-16 animate-fade-in">
            
            {/* Section 1: Visual Timeline */}
            <section>
              <div className="flex items-center justify-between mb-8">
                <h2 className="text-2xl font-serif font-bold text-white flex items-center gap-3">
                  <span className="bg-slate-800 text-slate-400 text-sm font-mono py-1 px-2 rounded">SEQ-01</span>
                  {t.timelineTitle}
                </h2>
                <button className="hidden sm:flex items-center gap-2 text-xs font-medium text-slate-400 hover:text-white transition-colors border border-slate-700 px-3 py-1.5 rounded hover:bg-slate-800">
                  <Download className="w-4 h-4" />
                  {t.export}
                </button>
              </div>
              <div className="bg-slate-950 rounded-2xl border border-slate-800 p-4 md:p-8 shadow-2xl shadow-black">
                <Timeline events={data.timeline} lang={lang} />
              </div>
            </section>

            {/* Section 2, 3, 4: Analysis Reports */}
            <section>
              <div className="flex items-center justify-between mb-8">
                <h2 className="text-2xl font-serif font-bold text-white flex items-center gap-3">
                  <span className="bg-slate-800 text-slate-400 text-sm font-mono py-1 px-2 rounded">SEQ-02</span>
                  {t.reportTitle}
                </h2>
              </div>
              <AnalysisSection data={data} lang={lang} />
            </section>

             {/* Disclaimer */}
             <footer className="border-t border-slate-800 pt-8 pb-12 text-center">
                <p className="text-xs text-slate-600 max-w-3xl mx-auto">
                  {t.disclaimer}
                </p>
             </footer>

          </div>
        )}

      </main>
    </div>
  );
};

export default App;